# Generated by Django 3.2.19 on 2023-07-29 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LibraryName', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=70)),
                ('AuthorName', models.CharField(max_length=70)),
                ('Library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onetomany.library')),
            ],
        ),
    ]
