# Generated by Django 3.2.19 on 2023-07-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('duration', models.IntegerField(default=600, help_text='Duration in seconds. Minimum: 1, Maximum: 600 (10 minutes)')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN-PROGRESS'), ('DONE', 'DONE')], default='TODO', max_length=30)),
            ],
        ),
    ]
